

application: ae-01-trivial
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers: 
- url: /.*
  static_files: website/LAYOUT.html
  upload: website/LAYOUT.html

- url: /.*
  static_dir: website